# Generated by Django 5.2.7 on 2025-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flutterwave_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
