# Generated by Django 5.2.7 on 2025-11-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_flutterwave_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webauthn_credential_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='webauthn_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='webauthn_sign_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
