# Generated by Django 5.2.7 on 2026-01-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_user_biometric_enabled_user_biometric_registered_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
