# Generated by Django 5.2.7 on 2026-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_device_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
