# Generated by Django 5.2.7 on 2025-12-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='van_account_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
