# Generated by Django 5.2.7 on 2025-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='flutterwave_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='provider',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('monnify', 'Monnify'), ('palmpay', 'PalmPay'), ('opay', 'OPay')], max_length=32),
        ),
    ]
