# Generated by Django 5.2.7 on 2025-11-15 16:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_flutterwave_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='metadata',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
