# Generated by Django 5.2.7 on 2025-10-27 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('palmpay', 'PalmPay'), ('paystack', 'Paystack'), ('monnify', 'Monnify'), ('opay', 'OPay'), ('flutterwave', 'Flutterwave')], max_length=32)),
                ('provider_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('account_name', models.CharField(blank=True, max_length=128, null=True)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('virtual_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallet.virtualaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='virtualaccount',
            index=models.Index(fields=['provider', 'provider_account_id'], name='wallet_virt_provide_ac3b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualaccount',
            index=models.Index(fields=['account_number'], name='wallet_virt_account_876d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['status'], name='wallet_depo_status_931183_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['created_at'], name='wallet_depo_created_2d0711_idx'),
        ),
    ]
