# Generated by Django 5.2.7 on 2025-12-09 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_van_account_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='virtualaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'account_number'), name='unique_provider_account_number'),
        ),
    ]
