# Generated by Django 5.2.7 on 2025-12-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_virtualaccount_unique_provider_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('airtime', 'Airtime'), ('data', 'Data'), ('gasfee', 'Gas Fee'), ('crypto', 'Crypto'), ('bonus', 'Bonus'), ('payment', 'Payment'), ('refund', 'Refund'), ('referral', 'Referral Bonus'), ('other', 'Other')], max_length=20),
        ),
    ]
