# Generated by Django 5.2.7 on 2025-12-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_add_provider_reference_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deposit',
            new_name='wallet_depo_provide_7f4022_idx',
            old_name='wallet_depo_provide_idx',
        ),
    ]
