# Generated by Django 5.2.7 on 2025-12-21 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_rename_wallet_depo_provide_idx_wallet_depo_provide_7f4022_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pin_verify_success', 'PIN Verification Success'), ('pin_verify_failed', 'PIN Verification Failed'), ('pin_setup', 'PIN Setup'), ('pin_change', 'PIN Change'), ('pin_reset_request', 'PIN Reset Request'), ('pin_reset_complete', 'PIN Reset Complete'), ('pin_locked', 'PIN Locked'), ('pin_unlocked', 'PIN Unlocked'), ('biometric_verify_success', 'Biometric Verification Success'), ('biometric_verify_failed', 'Biometric Verification Failed'), ('biometric_enrolled', 'Biometric Enrolled'), ('biometric_disabled', 'Biometric Disabled'), ('transaction_approved', 'Transaction Approved'), ('transaction_denied', 'Transaction Denied')], max_length=30)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('verification_method', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='wallet_tran_user_id_1524fa_idx'), models.Index(fields=['created_at'], name='wallet_tran_created_7f285b_idx')],
            },
        ),
    ]
