# Generated by Django 5.2.7 on 2025-12-26 11:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_transactionsecuritylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDepositExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Exchange rate to NGN', max_digits=12)),
                ('flutterwave_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.4'), help_text='Flutterwave processing fee percentage', max_digits=5)),
                ('platform_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Platform margin/profit percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Card Deposit Exchange Rate',
                'verbose_name_plural': 'Card Deposit Exchange Rates',
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='CardDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in foreign currency', max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=2, help_text='Exchange rate at transaction time', max_digits=12)),
                ('ngn_amount', models.DecimalField(decimal_places=2, help_text='Amount user receives in NGN', max_digits=12)),
                ('gross_ngn', models.DecimalField(decimal_places=2, help_text='Gross NGN before fees', max_digits=12)),
                ('flutterwave_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('platform_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('flutterwave_tx_ref', models.CharField(db_index=True, max_length=255, unique=True)),
                ('flutterwave_tx_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw Flutterwave response')),
                ('use_live_mode', models.BooleanField(default=False, help_text='Whether live or test mode was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Deposit',
                'verbose_name_plural': 'Card Deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='wallet_card_user_id_2eaca7_idx'), models.Index(fields=['flutterwave_tx_ref'], name='wallet_card_flutter_978a0a_idx'), models.Index(fields=['flutterwave_tx_id'], name='wallet_card_flutter_25ce7e_idx'), models.Index(fields=['created_at'], name='wallet_card_created_65a2b8_idx')],
            },
        ),
    ]
