# Generated by Django 5.2.7 on 2026-01-01 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_carddepositexchangerate_carddeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRetryQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_type', models.CharField(choices=[('card_deposit', 'Card Deposit'), ('flutterwave', 'Flutterwave'), ('palmpay', 'PalmPay'), ('paystack', 'Paystack'), ('9psb', '9PSB')], max_length=20)),
                ('tx_ref', models.CharField(db_index=True, help_text='Transaction reference', max_length=255)),
                ('payload', models.JSONField(help_text='Original webhook payload')),
                ('signature', models.CharField(blank=True, help_text='Webhook signature', max_length=512, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed_permanent', 'Failed - Permanent'), ('failed_transient', 'Failed - Transient')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5, help_text='Maximum number of retry attempts')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Next scheduled retry time', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_permanent_failure', models.BooleanField(default=False, help_text='True if failure is permanent and should not retry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Retry Queue',
                'verbose_name_plural': 'Webhook Retry Queue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook_type', 'status'], name='wallet_webh_webhook_e8e306_idx'), models.Index(fields=['tx_ref'], name='wallet_webh_tx_ref_a21dee_idx'), models.Index(fields=['status', 'next_retry_at'], name='wallet_webh_status_370370_idx'), models.Index(fields=['created_at'], name='wallet_webh_created_31d5b1_idx')],
            },
        ),
    ]
