# Generated by Django 5.2.7 on 2026-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0009_webhookretryqueue"),
    ]

    operations = [
        migrations.AddField(
            model_name="carddeposit",
            name="provider",
            field=models.CharField(
                choices=[("flutterwave", "Flutterwave"), ("fincra", "Fincra")],
                default="flutterwave",
                max_length=20,
            ),
        ),
    ]
