export const COUNTRY_DATA = [
  { code: "us", name: "United States", flag: "🇺🇸", dialCode: "1" },
  { code: "gb", name: "United Kingdom", flag: "🇬🇧", dialCode: "44" },
  { code: "ng", name: "Nigeria", flag: "🇳🇬", dialCode: "234" },
  { code: "in", name: "India", flag: "🇮🇳", dialCode: "91" },
  { code: "ca", name: "Canada", flag: "🇨🇦", dialCode: "1" },
  { code: "au", name: "Australia", flag: "🇦🇺", dialCode: "61" },
  { code: "de", name: "Germany", flag: "🇩🇪", dialCode: "49" },
  { code: "fr", name: "France", flag: "🇫🇷", dialCode: "33" },
  { code: "za", name: "South Africa", flag: "🇿🇦", dialCode: "27" },
  { code: "ke", name: "Kenya", flag: "🇰🇪", dialCode: "254" },
  { code: "br", name: "Brazil", flag: "🇧🇷", dialCode: "55" },
  { code: "mx", name: "Mexico", flag: "🇲🇽", dialCode: "52" },
  { code: "jp", name: "Japan", flag: "🇯🇵", dialCode: "81" },
  { code: "cn", name: "China", flag: "🇨🇳", dialCode: "86" },
  { code: "ru", name: "Russia", flag: "🇷🇺", dialCode: "7" },
  { code: "it", name: "Italy", flag: "🇮🇹", dialCode: "39" },
  { code: "es", name: "Spain", flag: "🇪🇸", dialCode: "34" },

  { code: "af", name: "Afghanistan", flag: "🇦🇫", dialCode: "93" },
  { code: "al", name: "Albania", flag: "🇦🇱", dialCode: "355" },
  { code: "dz", name: "Algeria", flag: "🇩🇿", dialCode: "213" },
  { code: "ad", name: "Andorra", flag: "🇦🇩", dialCode: "376" },
  { code: "ao", name: "Angola", flag: "🇦🇴", dialCode: "244" },
  { code: "ag", name: "Antigua and Barbuda", flag: "🇦🇬", dialCode: "1-268" },
  { code: "ar", name: "Argentina", flag: "🇦🇷", dialCode: "54" },
  { code: "am", name: "Armenia", flag: "🇦🇲", dialCode: "374" },
  { code: "at", name: "Austria", flag: "🇦🇹", dialCode: "43" },
  { code: "az", name: "Azerbaijan", flag: "🇦🇿", dialCode: "994" },
  { code: "bs", name: "Bahamas", flag: "🇧🇸", dialCode: "1-242" },
  { code: "bh", name: "Bahrain", flag: "🇧🇭", dialCode: "973" },
  { code: "bd", name: "Bangladesh", flag: "🇧🇩", dialCode: "880" },
  { code: "bb", name: "Barbados", flag: "🇧🇧", dialCode: "1-246" },
  { code: "by", name: "Belarus", flag: "🇧🇾", dialCode: "375" },
  { code: "be", name: "Belgium", flag: "🇧🇪", dialCode: "32" },
  { code: "bz", name: "Belize", flag: "🇧🇿", dialCode: "501" },
  { code: "bj", name: "Benin", flag: "🇧🇯", dialCode: "229" },
  { code: "bt", name: "Bhutan", flag: "🇧🇹", dialCode: "975" },
  { code: "bo", name: "Bolivia", flag: "🇧🇴", dialCode: "591" },
  { code: "ba", name: "Bosnia and Herzegovina", flag: "🇧🇦", dialCode: "387" },
  { code: "bw", name: "Botswana", flag: "🇧🇼", dialCode: "267" },
  { code: "bn", name: "Brunei", flag: "🇧🇳", dialCode: "673" },
  { code: "bg", name: "Bulgaria", flag: "🇧🇬", dialCode: "359" },
  { code: "bf", name: "Burkina Faso", flag: "🇧🇫", dialCode: "226" },
  { code: "bi", name: "Burundi", flag: "🇧🇮", dialCode: "257" },
  { code: "kh", name: "Cambodia", flag: "🇰🇭", dialCode: "855" },
  { code: "cm", name: "Cameroon", flag: "🇨🇲", dialCode: "237" },
  { code: "cv", name: "Cape Verde", flag: "🇨🇻", dialCode: "238" },
  { code: "cf", name: "Central African Republic", flag: "🇨🇫", dialCode: "236" },
  { code: "td", name: "Chad", flag: "🇹🇩", dialCode: "235" },
  { code: "cl", name: "Chile", flag: "🇨🇱", dialCode: "56" },
  { code: "co", name: "Colombia", flag: "🇨🇴", dialCode: "57" },
  { code: "km", name: "Comoros", flag: "🇰🇲", dialCode: "269" },
  { code: "cd", name: "Congo (DRC)", flag: "🇨🇩", dialCode: "243" },
  { code: "cg", name: "Congo (Republic)", flag: "🇨🇬", dialCode: "242" },
  { code: "cr", name: "Costa Rica", flag: "🇨🇷", dialCode: "506" },
  { code: "hr", name: "Croatia", flag: "🇭🇷", dialCode: "385" },
  { code: "cu", name: "Cuba", flag: "🇨🇺", dialCode: "53" },
  { code: "cy", name: "Cyprus", flag: "🇨🇾", dialCode: "357" },
  { code: "cz", name: "Czech Republic", flag: "🇨🇿", dialCode: "420" },
  { code: "dk", name: "Denmark", flag: "🇩🇰", dialCode: "45" },
  { code: "dj", name: "Djibouti", flag: "🇩🇯", dialCode: "253" },
  { code: "dm", name: "Dominica", flag: "🇩🇲", dialCode: "1-767" },
  { code: "do", name: "Dominican Republic", flag: "🇩🇴", dialCode: "1-809" },
  { code: "ec", name: "Ecuador", flag: "🇪🇨", dialCode: "593" },
  { code: "eg", name: "Egypt", flag: "🇪🇬", dialCode: "20" },
  { code: "sv", name: "El Salvador", flag: "🇸🇻", dialCode: "503" },
  { code: "gq", name: "Equatorial Guinea", flag: "🇬🇶", dialCode: "240" },
  { code: "er", name: "Eritrea", flag: "🇪🇷", dialCode: "291" },
  { code: "ee", name: "Estonia", flag: "🇪🇪", dialCode: "372" },
  { code: "sz", name: "Eswatini", flag: "🇸🇿", dialCode: "268" },
  { code: "et", name: "Ethiopia", flag: "🇪🇹", dialCode: "251" },
  { code: "fj", name: "Fiji", flag: "🇫🇯", dialCode: "679" },
  { code: "fi", name: "Finland", flag: "🇫🇮", dialCode: "358" },
  { code: "ga", name: "Gabon", flag: "🇬🇦", dialCode: "241" },
  { code: "gm", name: "Gambia", flag: "🇬🇲", dialCode: "220" },
  { code: "ge", name: "Georgia", flag: "🇬🇪", dialCode: "995" },
  { code: "gh", name: "Ghana", flag: "🇬🇭", dialCode: "233" },
  { code: "gr", name: "Greece", flag: "🇬🇷", dialCode: "30" },
  { code: "gd", name: "Grenada", flag: "🇬🇩", dialCode: "1-473" },
  { code: "gt", name: "Guatemala", flag: "🇬🇹", dialCode: "502" },
  { code: "gn", name: "Guinea", flag: "🇬🇳", dialCode: "224" },
  { code: "gw", name: "Guinea-Bissau", flag: "🇬🇼", dialCode: "245" },
  { code: "gy", name: "Guyana", flag: "🇬🇾", dialCode: "592" },
  { code: "ht", name: "Haiti", flag: "🇭🇹", dialCode: "509" },
  { code: "hn", name: "Honduras", flag: "🇭🇳", dialCode: "504" },
  { code: "hu", name: "Hungary", flag: "🇭🇺", dialCode: "36" },
  { code: "is", name: "Iceland", flag: "🇮🇸", dialCode: "354" },
  { code: "id", name: "Indonesia", flag: "🇮🇩", dialCode: "62" },
  { code: "ir", name: "Iran", flag: "🇮🇷", dialCode: "98" },
  { code: "iq", name: "Iraq", flag: "🇮🇶", dialCode: "964" },
  { code: "ie", name: "Ireland", flag: "🇮🇪", dialCode: "353" },
  { code: "il", name: "Israel", flag: "🇮🇱", dialCode: "972" },
  { code: "jm", name: "Jamaica", flag: "🇯🇲", dialCode: "1-876" },
  { code: "jo", name: "Jordan", flag: "🇯🇴", dialCode: "962" },
  { code: "kz", name: "Kazakhstan", flag: "🇰🇿", dialCode: "7" },
  { code: "ki", name: "Kiribati", flag: "🇰🇮", dialCode: "686" },
  { code: "kw", name: "Kuwait", flag: "🇰🇼", dialCode: "965" },
  { code: "kg", name: "Kyrgyzstan", flag: "🇰🇬", dialCode: "996" },
  { code: "la", name: "Laos", flag: "🇱🇦", dialCode: "856" },
  { code: "lv", name: "Latvia", flag: "🇱🇻", dialCode: "371" },
  { code: "lb", name: "Lebanon", flag: "🇱🇧", dialCode: "961" },
  { code: "ls", name: "Lesotho", flag: "🇱🇸", dialCode: "266" },
  { code: "lr", name: "Liberia", flag: "🇱🇷", dialCode: "231" },
  { code: "ly", name: "Libya", flag: "🇱🇾", dialCode: "218" },
  { code: "li", name: "Liechtenstein", flag: "🇱🇮", dialCode: "423" },
  { code: "lt", name: "Lithuania", flag: "🇱🇹", dialCode: "370" },
  { code: "lu", name: "Luxembourg", flag: "🇱🇺", dialCode: "352" },
  { code: "mg", name: "Madagascar", flag: "🇲🇬", dialCode: "261" },
  { code: "mw", name: "Malawi", flag: "🇲🇼", dialCode: "265" },
  { code: "my", name: "Malaysia", flag: "🇲🇾", dialCode: "60" },
  { code: "mv", name: "Maldives", flag: "🇲🇻", dialCode: "960" },
  { code: "ml", name: "Mali", flag: "🇲🇱", dialCode: "223" },
  { code: "mt", name: "Malta", flag: "🇲🇹", dialCode: "356" },
  { code: "mh", name: "Marshall Islands", flag: "🇲🇭", dialCode: "692" },
  { code: "mr", name: "Mauritania", flag: "🇲🇷", dialCode: "222" },
  { code: "mu", name: "Mauritius", flag: "🇲🇺", dialCode: "230" },
  { code: "fm", name: "Micronesia", flag: "🇫🇲", dialCode: "691" },
  { code: "md", name: "Moldova", flag: "🇲🇩", dialCode: "373" },
  { code: "mc", name: "Monaco", flag: "🇲🇨", dialCode: "377" },
  { code: "mn", name: "Mongolia", flag: "🇲🇳", dialCode: "976" },
  { code: "me", name: "Montenegro", flag: "🇲🇪", dialCode: "382" },
  { code: "ma", name: "Morocco", flag: "🇲🇦", dialCode: "212" },
  { code: "mz", name: "Mozambique", flag: "🇲🇿", dialCode: "258" },
  { code: "mm", name: "Myanmar", flag: "🇲🇲", dialCode: "95" },
  { code: "na", name: "Namibia", flag: "🇳🇦", dialCode: "264" },
  { code: "nr", name: "Nauru", flag: "🇳🇷", dialCode: "674" },
  { code: "np", name: "Nepal", flag: "🇳🇵", dialCode: "977" },
  { code: "nl", name: "Netherlands", flag: "🇳🇱", dialCode: "31" },
  { code: "nz", name: "New Zealand", flag: "🇳🇿", dialCode: "64" },
  { code: "ni", name: "Nicaragua", flag: "🇳🇮", dialCode: "505" },
  { code: "ne", name: "Niger", flag: "🇳🇪", dialCode: "227" },
  { code: "kp", name: "North Korea", flag: "🇰🇵", dialCode: "850" },
  { code: "no", name: "Norway", flag: "🇳🇴", dialCode: "47" },
  { code: "om", name: "Oman", flag: "🇴🇲", dialCode: "968" },
  { code: "pk", name: "Pakistan", flag: "🇵🇰", dialCode: "92" },
  { code: "pw", name: "Palau", flag: "🇵🇼", dialCode: "680" },
  { code: "pa", name: "Panama", flag: "🇵🇦", dialCode: "507" },
  { code: "pg", name: "Papua New Guinea", flag: "🇵🇬", dialCode: "675" },
  { code: "py", name: "Paraguay", flag: "🇵🇾", dialCode: "595" },
  { code: "pe", name: "Peru", flag: "🇵🇪", dialCode: "51" },
  { code: "ph", name: "Philippines", flag: "🇵🇭", dialCode: "63" },
  { code: "pl", name: "Poland", flag: "🇵🇱", dialCode: "48" },
  { code: "pt", name: "Portugal", flag: "🇵🇹", dialCode: "351" },
  { code: "qa", name: "Qatar", flag: "🇶🇦", dialCode: "974" },
    { code: "ro", name: "Romania", flag: "🇷🇴", dialCode: "40" },
  { code: "ru", name: "Russia", flag: "🇷🇺", dialCode: "7" },
  { code: "rw", name: "Rwanda", flag: "🇷🇼", dialCode: "250" },
  { code: "kn", name: "Saint Kitts and Nevis", flag: "🇰🇳", dialCode: "1-869" },
  { code: "lc", name: "Saint Lucia", flag: "🇱🇨", dialCode: "1-758" },
  { code: "vc", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", dialCode: "1-784" },
  { code: "ws", name: "Samoa", flag: "🇼🇸", dialCode: "685" },
  { code: "sm", name: "San Marino", flag: "🇸🇲", dialCode: "378" },
  { code: "st", name: "Sao Tome and Principe", flag: "🇸🇹", dialCode: "239" },
  { code: "sa", name: "Saudi Arabia", flag: "🇸🇦", dialCode: "966" },
  { code: "sn", name: "Senegal", flag: "🇸🇳", dialCode: "221" },
  { code: "rs", name: "Serbia", flag: "🇷🇸", dialCode: "381" },
  { code: "sc", name: "Seychelles", flag: "🇸🇨", dialCode: "248" },
  { code: "sl", name: "Sierra Leone", flag: "🇸🇱", dialCode: "232" },
  { code: "sg", name: "Singapore", flag: "🇸🇬", dialCode: "65" },
  { code: "sk", name: "Slovakia", flag: "🇸🇰", dialCode: "421" },
  { code: "si", name: "Slovenia", flag: "🇸🇮", dialCode: "386" },
  { code: "sb", name: "Solomon Islands", flag: "🇸🇧", dialCode: "677" },
  { code: "so", name: "Somalia", flag: "🇸🇴", dialCode: "252" },
  { code: "za", name: "South Africa", flag: "🇿🇦", dialCode: "27" },
  { code: "kr", name: "South Korea", flag: "🇰🇷", dialCode: "82" },
  { code: "ss", name: "South Sudan", flag: "🇸🇸", dialCode: "211" },
  { code: "es", name: "Spain", flag: "🇪🇸", dialCode: "34" },
  { code: "lk", name: "Sri Lanka", flag: "🇱🇰", dialCode: "94" },
  { code: "sd", name: "Sudan", flag: "🇸🇩", dialCode: "249" },
  { code: "sr", name: "Suriname", flag: "🇸🇷", dialCode: "597" },
  { code: "se", name: "Sweden", flag: "🇸🇪", dialCode: "46" },
  { code: "ch", name: "Switzerland", flag: "🇨🇭", dialCode: "41" },
  { code: "sy", name: "Syria", flag: "🇸🇾", dialCode: "963" },
  { code: "tw", name: "Taiwan", flag: "🇹🇼", dialCode: "886" },
  { code: "tj", name: "Tajikistan", flag: "🇹🇯", dialCode: "992" },
  { code: "tz", name: "Tanzania", flag: "🇹🇿", dialCode: "255" },
  { code: "th", name: "Thailand", flag: "🇹🇭", dialCode: "66" },
  { code: "tl", name: "Timor-Leste", flag: "🇹🇱", dialCode: "670" },
  { code: "tg", name: "Togo", flag: "🇹🇬", dialCode: "228" },
  { code: "to", name: "Tonga", flag: "🇹🇴", dialCode: "676" },
  { code: "tt", name: "Trinidad and Tobago", flag: "🇹🇹", dialCode: "1-868" },
  { code: "tn", name: "Tunisia", flag: "🇹🇳", dialCode: "216" },
  { code: "tr", name: "Turkey", flag: "🇹🇷", dialCode: "90" },
  { code: "tm", name: "Turkmenistan", flag: "🇹🇲", dialCode: "993" },
  { code: "tv", name: "Tuvalu", flag: "🇹🇻", dialCode: "688" },
  { code: "ug", name: "Uganda", flag: "🇺🇬", dialCode: "256" },
  { code: "ua", name: "Ukraine", flag: "🇺🇦", dialCode: "380" },
  { code: "ae", name: "United Arab Emirates", flag: "🇦🇪", dialCode: "971" },
  { code: "uy", name: "Uruguay", flag: "🇺🇾", dialCode: "598" },
  { code: "uz", name: "Uzbekistan", flag: "🇺🇿", dialCode: "998" },
  { code: "vu", name: "Vanuatu", flag: "🇻🇺", dialCode: "678" },
  { code: "va", name: "Vatican City", flag: "🇻🇦", dialCode: "379" },
  { code: "ve", name: "Venezuela", flag: "🇻🇪", dialCode: "58" },
  { code: "vn", name: "Vietnam", flag: "🇻🇳", dialCode: "84" },
  { code: "ye", name: "Yemen", flag: "🇾🇪", dialCode: "967" },
  { code: "zm", name: "Zambia", flag: "🇿🇲", dialCode: "260" },
  { code: "zw", name: "Zimbabwe", flag: "🇿🇼", dialCode: "263" },

  // Small territories & dependencies
  { code: "ai", name: "Anguilla", flag: "🇦🇮", dialCode: "1-264" },
  { code: "bm", name: "Bermuda", flag: "🇧🇲", dialCode: "1-441" },
  { code: "cw", name: "Curaçao", flag: "🇨🇼", dialCode: "599" },
  { code: "fk", name: "Falkland Islands", flag: "🇫🇰", dialCode: "500" },
  { code: "gf", name: "French Guiana", flag: "🇬🇫", dialCode: "594" },
  { code: "gp", name: "Guadeloupe", flag: "🇬🇵", dialCode: "590" },
  { code: "mq", name: "Martinique", flag: "🇲🇶", dialCode: "596" },
  { code: "nc", name: "New Caledonia", flag: "🇳🇨", dialCode: "687" },
  { code: "re", name: "Réunion", flag: "🇷🇪", dialCode: "262" },
  { code: "bl", name: "Saint Barthélemy", flag: "🇧🇱", dialCode: "590" },
  { code: "mf", name: "Saint Martin", flag: "🇲🇫", dialCode: "590" },
  { code: "sx", name: "Sint Maarten", flag: "🇸🇽", dialCode: "1-721" },
  { code: "tc", name: "Turks and Caicos Islands", flag: "🇹🇨", dialCode: "1-649" },
  { code: "vi", name: "U.S. Virgin Islands", flag: "🇻🇮", dialCode: "1-340" }
];
