# Generated by Django 5.2.7 on 2025-12-09 21:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('welcome', 'Welcome'), ('referral', 'Referral'), ('promo', 'Promo'), ('manual', 'Manual'), ('cashback', 'Cashback'), ('deposit', 'Deposit Bonus'), ('airtime_data', 'Airtime/Data Only')], max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('default_expiry_days', models.IntegerField(blank=True, null=True)),
                ('default_rules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('used', 'Used'), ('expired', 'Expired'), ('reversed', 'Reversed')], default='locked', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL)),
                ('bonus_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='rewards.bonustype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
