# Generated by Django 5.2.7 on 2025-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustype',
            name='name',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('referral', 'Referral'), ('promo', 'Promo'), ('loyalty', 'Loyalty'), ('seasonal', 'Seasonal'), ('manual', 'Manual'), ('cashback', 'Cashback'), ('deposit', 'Deposit Bonus'), ('airtime_data', 'Airtime/Data Only')], max_length=50, unique=True),
        ),
    ]
