# Generated by Django 5.2.7 on 2025-11-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeratemargin',
            name='margin_type',
            field=models.CharField(choices=[('buy', 'Buy Margin'), ('sell', 'Sell Margin')], default='buy', max_length=10),
        ),
        migrations.AlterField(
            model_name='exchangeratemargin',
            name='currency_pair',
            field=models.CharField(default='USDT/NGN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='exchangeratemargin',
            unique_together={('currency_pair', 'margin_type')},
        ),
    ]
