# Generated by Django 5.2.7 on 2025-11-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0002_exchangeratemargin_margin_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeratemargin',
            options={'verbose_name': 'Exchange Rate Margin', 'verbose_name_plural': 'Exchange Rate Margins'},
        ),
    ]
