# Generated by Django 5.2.7 on 2025-11-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0003_alter_exchangeratemargin_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeInfo',
        ),
    ]
