# Generated by Django 5.2.7 on 2025-11-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0004_delete_exchangeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsellorder',
            name='source',
            field=models.CharField(choices=[('Binance', 'Binance'), ('Bybit', 'Bybit'), ('Mexc', 'MEXC'), ('Gate.io', 'Gate.io'), ('Bitget', 'Bitget'), ('Web3 wallet', 'Web3 wallet')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='gasfee.asset')),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
