# Generated by Django 5.2.7 on 2025-11-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0005_alter_assetsellorder_source_assetprice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetPrice',
        ),
    ]
