# Generated by Django 5.2.7 on 2025-11-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0006_delete_assetprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='last_known_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='last_price_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
