# Generated by Django 5.2.7 on 2025-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0007_crypto_last_known_price_crypto_last_price_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='coingecko_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
