# Generated by Django - Manual creation for TransactionMonitoring model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gasfee', '0008_asset_coingecko_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('severity', models.CharField(default='low', max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionmonitoring',
            index=models.Index(fields=['user', 'created_at'], name='gasfee_tran_user_id_4a8b34_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmonitoring',
            index=models.Index(fields=['event_type', 'severity'], name='gasfee_tran_event_t_8f7e21_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmonitoring',
            index=models.Index(fields=['reviewed'], name='gasfee_tran_reviewe_1a9c42_idx'),
        ),
    ]
