# Generated by Django 5.2.7 on 2026-01-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0009_transactionmonitoring'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transactionmonitoring',
            new_name='gasfee_tran_user_id_1d852d_idx',
            old_name='gasfee_tran_user_id_4a8b34_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionmonitoring',
            new_name='gasfee_tran_event_t_12defc_idx',
            old_name='gasfee_tran_event_t_8f7e21_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionmonitoring',
            new_name='gasfee_tran_reviewe_d092e1_idx',
            old_name='gasfee_tran_reviewe_1a9c42_idx',
        ),
    ]
