# Generated by Django 5.2.7 on 2026-01-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_enabled', models.BooleanField(default=False, help_text='Enable maintenance mode for the entire application')),
                ('maintenance_message', models.CharField(default='We are currently performing scheduled maintenance. Please check back soon.', help_text='Custom message to display during maintenance', max_length=500)),
                ('maintenance_start_time', models.DateTimeField(blank=True, help_text='When maintenance mode was enabled', null=True)),
                ('maintenance_end_time', models.DateTimeField(blank=True, help_text='Estimated time when maintenance will end', null=True)),
                ('show_countdown', models.BooleanField(default=True, help_text='Show countdown timer on maintenance page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
